### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by evandrix** [IagoLast/Exquisite#2]
after `sudo npm i --unsafe-perm=true exquisite-sst`, invoking `exquisite-sst` produces the following error message:
```
TypeError: Cannot read property 'close' of undefined
    at Object.test (/usr/local/lib/node_modules/exquisite-sst/src/exquisite.js:22:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/exquisite-sst/bin/exquisite.js:9:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by IagoLast** [comment]
The error is because you are using the program with no parameters.

In any case the error is not very descriptive, is now solved in https://github.com/IagoLast/Exquisite/commit/b779f1f037ef99dbcdfe6a97f19f9e6ed4996555 with a better error message:

```bash
Error: Error: url parameter was not provided.
```
